name: Testes

on:
  push:
    branches:
      - main
      - developer

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:

      - name: print DATABASEurl context as json
        run: |
          echo ${{ toJson(secrets.DATABASEURL) }}
