name: Testes

on:
  push:
    branches:
      - main
      - developer

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Install dependencies
        run: npm ci

      - name: print secret context as json
        run: |
          echo ${{ toJson(secrets) }}
