name: Testes

on:
  push:
    branches:
      - main
      - developer
env:
  DATABASE_URL: ${{ secrets.DATABASEURL }}
jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Install dependencies
        run: npm ci
      - name : database url
        run: echo $DATABASE_URL
      - name : Prisma Init
        run: npx prisma migrate dev --name init
      - name: Run tests  
        run: npm test 
